branches:
  only:
    - master

language: node_js
node_js:
  - 10
os:
  - linux

cache:
  npm: true
  override:
    - npm ci

dist: xenial
services:
  - xvfb
addons:
    chrome: stable

before_install:
  - export DISPLAY=:99.0
  - npm install -g greenkeeper-lockfile
  - npm install -g codecov

script: 
  - ng build atft
  - ng lint
  - ng test --watch=false --code-coverage

after_success:
  - codecov

before_deploy:
  # Setup files to be deploy to gh-pages in ./dist/gh-pages-deploy

  # 1. Compile, minify and deploy Angular demo application
  - ng build --prod --base-href "https://makimenko.github.io/angular-template-for-threejs/demo/" --output-path ./dist/gh-pages-deploy/demo

  # 2. Generate API documentation
  - npm install -g @compodoc/compodoc
  - compodoc -p src/tsconfig.app.json -d dist/gh-pages-deploy

  # 3. Generate Storybook
  - npx build-storybook -c .storybook -o ./dist/gh-pages-deploy/storybook

deploy:
  provider: pages
  local-dir: dist/gh-pages-deploy
  skip-cleanup: true
  github-token: $GITHUB_PAGES_DEPLOYMENT_TOKEN
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages