name: CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install project dependencies
      run: npm ci
    - name: Build atft library
      run: npm run build-atft
    - name: Build project
      run: npm run build-prod
    - name: Test
      run: npm run test
    - name: Linting
      run: npm run lint


