name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install project dependencies
      run: npm ci
    - name: Build atft library
      run: npx ng build atft
    - name: Build prod
      run: npx ng build --prod --base-href "https://makimenko.github.io/angular-template-for-threejs/demo/" --output-path ./dist/gh-pages-deploy/demo
    - name: Generate documentation
      run: npx compodoc -p projects/atft/tsconfig.lib.json -d dist/gh-pages-deploy
    - name: Build storybook
      run: npx build-storybook -c .storybook -o ./dist/gh-pages-deploy/storybook
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install project dependencies
        run: npm ci
      - name: Build atft library
        run: npx ng build atft
      - name: Test
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 &
          export DISPLAY=:99
          npx ng test --watch=false --code-coverage
      - name: Code coverage
        run: npx codecov
