name: CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Project dependencies
      run: npm ci
  lib:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
    - name: Build atft library
      run: npx build-atft
  build:
    needs: [lib]
    runs-on: ubuntu-latest
    steps:
    - name: Build project
      run: npx build-prod
  test:
    needs: [lib]
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: npx test
  lint:
    needs: [lib]
    runs-on: ubuntu-latest
    steps:
    - name: Linting
      run: npx lint


