name: CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name:
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install project dependencies
      run: npm ci
    - name: Build atft library
      run: npx ng build atft
    - name: Test
      run: npm test
      env:
        CI: true
        DISPLAY: ":99.0"
