name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM Install
      run: |
        npm ci
        export DISPLAY=:99.0
        npm install -g greenkeeper-lockfile
        npm install -g codecov
      env:
        CI: true
    - name: Build
      run: |
        ng build atft
        ng lint
        ng test --watch=false --code-coverage
        ng build --prod --base-href "https://makimenko.github.io/angular-template-for-threejs/demo/" --output-path ./dist/gh-pages-deploy/demo
        npm install -g @compodoc/compodoc
        compodoc -p projects/atft/tsconfig.lib.json -d dist/gh-pages-deploy
        npx build-storybook -c .storybook -o ./dist/gh-pages-deploy/storybook
      env:
        CI: true
        
        
